apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: g
  namespace: aura
  labels:
    team: aura
spec:
  image: ghcr.io/navikt/g/g:{{ TAG }}
  port: 9292
  ingresses:
    - https://g.nav.no
  tracing:
    enabled: true
