apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: g
  namespace: aura
  labels:
    team: aura
spec:
  image: ghcr.io/navikt/g:{{ TAG }}
  port: 8000
  liveness:
    path: /isalive
    port: 8000
    initialDelay: 20
    timeout: 60
  readiness:
    path: /isready
    port: 8000
    initialDelay: 20
    timeout: 60
  ingresses:
    - https://g.nav.no
  tracing:
    enabled: true
