name: Linting
on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: rustup component add rustfmt # clippy
      # not working due to errors with non-ascii identifiers
      #- name: Build
      #  run: cargo clippy -- -D warnings -A=E0658
      - name: Run tests
        run: cargo fmt -- --check
