name: Linting
on: push

jobs:
  linting:
    name: Run Rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - run: |
          gem install bundler
          bundler install --without default 
      - run: rubocop
